
services:
  icinga-agent:
    image: icinga/icinga2
    container_name: icinga-agent
    hostname: icinga-agent
    ports:
      - 5665:5665
    volumes:
      - ./data/agent:/data
      - ./data/agent/ca.crt:/var/lib/icinga2/certs/ca.crt
    restart: unless-stopped
    environment:
      - ICINGA_ZONE=icinga-agent
      - ICINGA_ENDPOINT=icinga-master,icinga-master,5665
      - ICINGA_CACERT_FILE=/data/icinga-ca.crt
      - ICINGA_TICKET_FILE=/data/icinga-agent.ticket
