
networks:
  icinga:
    enable_ipv6: true
    driver: bridge

services:
  icinga-master:
    image: icinga/icinga2
    container_name: icinga-master
    hostname: icinga-master
    networks:
      - icinga
    ports:
      - 5665:5665
    volumes:
      - ./data/master:/data
      - ./data/msmtp/msmtprc:/etc/msmtprc:ro
      - ./data/msmtp/msmtp.log:/var/log/msmtp.log
    restart: unless-stopped
    environment:
      - ICINGA_MASTER=1
