version: '3.8'

networks:
  icinga:
    driver: bridge

services:

  redis-icingadb:
    image: redis
    container_name: redis-icingadb
    networks:
      - icinga
    restart: unless-stopped

  mariadb-icingadb:
    image: mariadb
    container_name: mariadb-icingadb
    networks:
      - icinga
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=1
      - MYSQL_DATABASE=icingadb
      - MYSQL_USER=icingadb
      - MYSQL_PASSWORD=123456
    restart: unless-stopped

  mariadb-icingaweb:
    image: mariadb
    container_name: mariadb-icingaweb
    networks:
      - icinga
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=1
      - MYSQL_DATABASE=icingaweb
      - MYSQL_USER=icingaweb
      - MYSQL_PASSWORD=123456
    restart: unless-stopped

  icingadb:
    image: icinga/icingadb
    container_name: icingadb
    networks:
      - icinga
    restart: always
    environment:
      - ICINGADB_REDIS_HOST=redis-icingadb
      - ICINGADB_REDIS_PORT=6379
      - ICINGADB_REDIS_PASSWORD=123456
      - ICINGADB_DATABASE_HOST=mariadb-icingadb
      - ICINGADB_DATABASE_PORT=3306
      - ICINGADB_DATABASE_DATABASE=icingadb
      - ICINGADB_DATABASE_USER=icingadb
      - ICINGADB_DATABASE_PASSWORD=123456
