version: '3.8'

networks:
  icinga:
    driver: bridge

services:
  icingaweb2:
    image: icinga/icingaweb2
    container_name: icingaweb2
    hostname: icingaweb2
    ports:
      - 80:8080
    networks:
      - icinga
    volumes:
      - ./data/web:/data
    restart: unless-stopped
    environment:
      - icingaweb.enabledModules=icingadb
      - icingaweb.passwords.icingaweb2.icingaadmin=123456
      - icingaweb.authentication.icingaweb2.backend=db
      - icingaweb.authentication.icingaweb2.resource=icingaweb_db
      - icingaweb.config.global.config_backend=db
      - icingaweb.config.global.config_resource=icingaweb_db
      - icingaweb.config.logging.log=php
      - icingaweb.groups.icingaweb2.backend=db
      - icingaweb.groups.icingaweb2.resource=icingaweb_db
      - icingaweb.modules.icingadb.config.icingadb.resource=icingadb
      - icingaweb.modules.icingadb.redis.redis1.host=redis-icingadb
      - icingaweb.modules.icingadb.redis.redis1.port=6379
      - icingaweb.modules.icingadb.commandtransports.icinga2.transport=api
      - icingaweb.modules.icingadb.commandtransports.icinga2.host=icinga-master
      - icingaweb.modules.icingadb.commandtransports.icinga2.username=root
      - icingaweb.modules.icingadb.commandtransports.icinga2.password=123456
      - icingaweb.resources.icingaweb_db.type=db
      - icingaweb.resources.icingaweb_db.db=mysql
      - icingaweb.resources.icingaweb_db.host=mariadb-icingaweb  # Or mariadb-icingadb if shared
      - icingaweb.resources.icingaweb_db.dbname=icingaweb
      - icingaweb.resources.icingaweb_db.username=icingaweb
      - icingaweb.resources.icingaweb_db.password=123456
      - icingaweb.resources.icingaweb_db.charset=utf8mb4
      - icingaweb.resources.icingadb.type=db
      - icingaweb.resources.icingadb.db=mysql
      - icingaweb.resources.icingadb.host=mariadb-icingadb
      - icingaweb.resources.icingadb.dbname=icingadb
      - icingaweb.resources.icingadb.username=icingadb
      - icingaweb.resources.icingadb.password=123456
      - icingaweb.resources.icingadb.charset=utf8mb4
      - icingaweb.roles.Administrators.users=icingaadmin
      - icingaweb.roles.Administrators.permissions=*
      - icingaweb.roles.Administrators.groups=Administrators
